version: '3.7'

services:

  sample:
    container_name: frontend:dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 4040:4040
    environment:
      - CHOKIDAR_USEPOLLING=true